driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: fedora-25

suites:
- name: remi
  run_list:
  - recipe[yum-remi-chef::remi]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true

- name: remi-safe
  run_list:
  - recipe[yum-remi-chef::remi-safe]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
  excludes:
  - fedora-25

- name: remi-php55
  run_list:
  - recipe[yum-remi-chef::remi-php55]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php55:
        enabled: true
        managed: true
  excludes:
  - fedora-25

- name: remi-php56
  run_list:
  - recipe[yum-remi-chef::remi-php56]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php56:
        enabled: true
        managed: true
  excludes:
  - fedora-25

- name: remi-php70
  run_list:
  - recipe[yum-remi-chef::remi-php70]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php70:
        enabled: true
        managed: true

- name: remi-php71
  run_list:
  - recipe[yum-remi-chef::remi-php71]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php71:
        enabled: true
        managed: true
