driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts net-tools

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts net-tools

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which net-tools chkconfig

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which net-tools chkconfig passwd

suites:
- name: remi
  run_list:
  - recipe[yum-remi-chef::remi]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true

- name: remi-safe
  run_list:
  - recipe[yum-remi-chef::remi-safe]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
  excludes:
  - centos-5
  - fedora-latest

- name: remi-php55
  run_list:
  - recipe[yum-remi-chef::remi-php55]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php55:
        enabled: true
        managed: true
  excludes:
  - fedora-latest

- name: remi-php56
  run_list:
  - recipe[yum-remi-chef::remi-php56]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php56:
        enabled: true
        managed: true
  excludes:
  - fedora-latest

- name: remi-php70
  run_list:
  - recipe[yum-remi-chef::remi-php70]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php70:
        enabled: true
        managed: true
  excludes:
  - centos-5

- name: remi-php71
  run_list:
  - recipe[yum-remi-chef::remi-php71]
  - recipe[test::default]
  attributes:
    yum:
      remi:
        enabled: true
        managed: true
      remi-php71:
        enabled: true
        managed: true
  excludes:
  - centos-5
