# Rubocop todo:
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/remi-php55/default_spec.rb'
    - 'test/integration/remi-php56/default_spec.rb'
    - 'test/integration/remi-php70/default_spec.rb'
    - 'test/integration/remi/default_spec.rb'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 161

# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts.
Style/FileName:
  Exclude:
    - 'attributes/remi-debuginfo.rb'
    - 'attributes/remi-php55-debuginfo.rb'
    - 'attributes/remi-php55.rb'
    - 'attributes/remi-php56-debuginfo.rb'
    - 'attributes/remi-php56.rb'
    - 'attributes/remi-php70-debuginfo.rb'
    - 'attributes/remi-php70.rb'
    - 'attributes/remi-test-debuginfo.rb'
    - 'attributes/remi-test.rb'
    - 'recipes/remi-php55.rb'
    - 'recipes/remi-php56.rb'
    - 'recipes/remi-php70.rb'
    - 'recipes/remi-test.rb'
