sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=remi-centos-6
  - INSTANCE=remi-centos-7
  - INSTANCE=remi-fedora-28
  - INSTANCE=remi-safe-centos-6
  - INSTANCE=remi-safe-centos-7
  - INSTANCE=remi-php55-centos-6
  - INSTANCE=remi-php55-centos-7
  - INSTANCE=remi-php56-centos-6
  - INSTANCE=remi-php56-centos-7
  - INSTANCE=remi-php70-centos-6
  - INSTANCE=remi-php70-centos-7
  - INSTANCE=remi-php70-fedora-28
  - INSTANCE=remi-php71-centos-6
  - INSTANCE=remi-php71-centos-7
  - INSTANCE=remi-php71-fedora-28
  - INSTANCE=remi-php72-centos-6
  - INSTANCE=remi-php72-centos-7
  - INSTANCE=remi-php72-fedora-28

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
